# Generated by Django 4.1.1 on 2022-11-02 22:15

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Category",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=64)),
            ],
            options={
                "verbose_name_plural": "categories",
            },
        ),
        migrations.CreateModel(
            name="Job",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created", models.DateTimeField(auto_now_add=True)),
                ("modified", models.DateTimeField(auto_now=True)),
            ],
            options={
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="NoteTemplate",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("path", models.CharField(max_length=64)),
                ("template", models.CharField(max_length=256)),
            ],
        ),
        migrations.CreateModel(
            name="Station",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=64)),
            ],
        ),
        migrations.CreateModel(
            name="Task",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=64)),
                ("instructions", models.TextField(blank=True)),
                (
                    "stations",
                    models.ManyToManyField(
                        blank=True, related_name="tasks", to="iris.station"
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="TaskConsolidation",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="TaskSpawn",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "closing_task",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="spawns",
                        to="iris.task",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Worker",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "picture",
                    models.ImageField(
                        blank=True,
                        height_field="picture_height",
                        null=True,
                        upload_to="worker_pictures/",
                        width_field="picture_width",
                    ),
                ),
                ("picture_height", models.IntegerField(editable=False, null=True)),
                ("picture_width", models.IntegerField(editable=False, null=True)),
                (
                    "user",
                    models.OneToOneField(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Work",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created", models.DateTimeField(auto_now_add=True)),
                ("modified", models.DateTimeField(auto_now=True)),
                ("cancel_time", models.DateTimeField(editable=False, null=True)),
                ("cancel_reason", models.CharField(editable=False, max_length=256)),
                ("notes", models.TextField(blank=True)),
                (
                    "category",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="works",
                        to="iris.category",
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="TaskSpawnSpawnedTasks",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "task",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.RESTRICT, to="iris.task"
                    ),
                ),
                (
                    "task_spawn",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="iris.taskspawn"
                    ),
                ),
            ],
        ),
        migrations.AddField(
            model_name="taskspawn",
            name="spawned_tasks",
            field=models.ManyToManyField(
                blank=True,
                related_name="spawned_by_tasks",
                through="iris.TaskSpawnSpawnedTasks",
                to="iris.task",
            ),
        ),
        migrations.CreateModel(
            name="TaskConsolidationSpawnedTasks",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "task",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.RESTRICT, to="iris.task"
                    ),
                ),
                (
                    "task_consolidation",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="iris.taskconsolidation",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="TaskConsolidationClosingTasks",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "task",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.RESTRICT, to="iris.task"
                    ),
                ),
                (
                    "task_consolidation",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="iris.taskconsolidation",
                    ),
                ),
            ],
        ),
        migrations.AddField(
            model_name="taskconsolidation",
            name="closing_tasks",
            field=models.ManyToManyField(
                related_name="consolidations",
                through="iris.TaskConsolidationClosingTasks",
                to="iris.task",
            ),
        ),
        migrations.AddField(
            model_name="taskconsolidation",
            name="spawned_tasks",
            field=models.ManyToManyField(
                blank=True,
                related_name="spawned_by_consolidation",
                through="iris.TaskConsolidationSpawnedTasks",
                to="iris.task",
            ),
        ),
        migrations.CreateModel(
            name="Suspension",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created", models.DateTimeField(auto_now_add=True)),
                ("modified", models.DateTimeField(auto_now=True)),
                ("notes", models.TextField(blank=True)),
                (
                    "job",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="suspensions",
                        to="iris.job",
                    ),
                ),
                (
                    "worker",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.RESTRICT, to="iris.worker"
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="Priority",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created", models.DateTimeField(auto_now_add=True)),
                ("modified", models.DateTimeField(auto_now=True)),
                ("notes", models.TextField(blank=True)),
                ("from_date", models.DateTimeField(default=django.utils.timezone.now)),
                ("score", models.IntegerField()),
                (
                    "job",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="priorities",
                        to="iris.job",
                    ),
                ),
                (
                    "worker",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.RESTRICT, to="iris.worker"
                    ),
                ),
            ],
            options={
                "verbose_name_plural": "priorities",
            },
        ),
        migrations.AddField(
            model_name="job",
            name="task",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.RESTRICT,
                related_name="jobs",
                to="iris.task",
            ),
        ),
        migrations.AddField(
            model_name="job",
            name="work",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.RESTRICT,
                related_name="jobs",
                to="iris.work",
            ),
        ),
        migrations.CreateModel(
            name="Delay",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created", models.DateTimeField(auto_now_add=True)),
                ("modified", models.DateTimeField(auto_now=True)),
                ("notes", models.TextField(blank=True)),
                ("time", models.DurationField()),
                (
                    "job",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="delays",
                        to="iris.job",
                    ),
                ),
                (
                    "worker",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.RESTRICT, to="iris.worker"
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="Commit",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created", models.DateTimeField(auto_now_add=True)),
                ("modified", models.DateTimeField(auto_now=True)),
                ("notes", models.TextField(blank=True)),
                (
                    "job",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE, to="iris.job"
                    ),
                ),
                (
                    "worker",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.RESTRICT, to="iris.worker"
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="CategorySpawnedTasks",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "category",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="iris.category"
                    ),
                ),
                (
                    "task",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.RESTRICT, to="iris.task"
                    ),
                ),
            ],
        ),
        migrations.AddField(
            model_name="category",
            name="spawned_tasks",
            field=models.ManyToManyField(
                blank=True,
                related_name="spawned_by_categories",
                through="iris.CategorySpawnedTasks",
                to="iris.task",
            ),
        ),
    ]
