# Generated by Django 4.1.1 on 2022-11-02 22:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("iris", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="task",
            name="average_hours",
        ),
    ]
