# Generated by Django 4.1.1 on 2022-11-02 22:49

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("iris", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="worker",
            name="picture",
        ),
        migrations.RemoveField(
            model_name="worker",
            name="picture_height",
        ),
        migrations.RemoveField(
            model_name="worker",
            name="picture_width",
        ),
    ]
