# Generated by Django 4.1.1 on 2022-11-15 19:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("iris", "0003_alter_commit_worker_alter_delay_worker_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="work",
            name="description",
            field=models.CharField(blank=True, max_length=128),
        ),
    ]
