# Generated by Django 4.1.1 on 2022-11-22 10:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("iris", "0004_work_description"),
    ]

    operations = [
        migrations.AddField(
            model_name="work",
            name="quantity",
            field=models.IntegerField(default=1),
        ),
    ]
