# Generated by Django 4.1.1 on 2022-11-22 11:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("iris", "0005_work_quantity"),
    ]

    operations = [
        migrations.DeleteModel(
            name="Priority",
        ),
    ]
