# Generated by Django 4.1.1 on 2022-11-22 11:18

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("iris", "0006_delete_priority"),
    ]

    operations = [
        migrations.AddField(
            model_name="work",
            name="has_priority",
            field=models.BooleanField(default=False),
        ),
    ]
