# Generated by Django 4.1.1 on 2023-02-07 19:05

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("iris", "0009_remove_delay_time_delay_duration_and_more"),
    ]

    operations = [
        migrations.DeleteModel(
            name="Category",
        ),
        migrations.DeleteModel(
            name="Job",
        ),
        migrations.DeleteModel(
            name="NoteTemplate",
        ),
        migrations.DeleteModel(
            name="Station",
        ),
        migrations.DeleteModel(
            name="Task",
        ),
        migrations.DeleteModel(
            name="TaskConsolidation",
        ),
        migrations.DeleteModel(
            name="TaskSpawn",
        ),
        migrations.DeleteModel(
            name="Worker",
        ),
        migrations.DeleteModel(
            name="Work",
        ),
        migrations.DeleteModel(
            name="TaskSpawnSpawnedTasks",
        ),
        migrations.DeleteModel(
            name="TaskConsolidationSpawnedTasks",
        ),
        migrations.DeleteModel(
            name="TaskConsolidationClosingTasks",
        ),
        migrations.DeleteModel(
            name="Suspension",
        ),
        migrations.DeleteModel(
            name="Delay",
        ),
        migrations.DeleteModel(
            name="Commit",
        ),
        migrations.DeleteModel(
            name="CategorySpawnedTasks",
        ),
    ]
