# Generated by Django 4.2.1 on 2023-05-26 20:46

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("iris", "0012_reset_db"),
    ]

    operations = [
        migrations.CreateModel(
            name="Item",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created",
                    models.DateTimeField(auto_now_add=True, verbose_name="created"),
                ),
                (
                    "modified",
                    models.DateTimeField(auto_now=True, verbose_name="modified"),
                ),
                (
                    "cancel_time",
                    models.DateTimeField(
                        editable=False, null=True, verbose_name="cancelation time"
                    ),
                ),
                (
                    "cancel_reason",
                    models.CharField(
                        editable=False,
                        max_length=256,
                        verbose_name="cancelation reason",
                    ),
                ),
                ("notes", models.TextField(blank=True, verbose_name="notes")),
                (
                    "description",
                    models.CharField(
                        blank=True, max_length=128, verbose_name="description"
                    ),
                ),
                (
                    "quantity",
                    models.IntegerField(
                        default=1,
                        validators=[django.core.validators.MinValueValidator(1)],
                        verbose_name="quantity",
                    ),
                ),
                (
                    "has_priority",
                    models.BooleanField(default=False, verbose_name="has priority"),
                ),
            ],
            options={
                "verbose_name": "item",
                "verbose_name_plural": "items",
            },
        ),
        migrations.CreateModel(
            name="NoteTemplate",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("path", models.CharField(max_length=64, verbose_name="path")),
                ("template", models.CharField(max_length=256, verbose_name="template")),
            ],
            options={
                "verbose_name": "note template",
                "verbose_name_plural": "note templates",
            },
        ),
        migrations.CreateModel(
            name="Process",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=64, verbose_name="name")),
            ],
            options={
                "verbose_name": "process",
                "verbose_name_plural": "processes",
            },
        ),
        migrations.CreateModel(
            name="Station",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=64, verbose_name="name")),
            ],
            options={
                "verbose_name": "station",
                "verbose_name_plural": "stations",
            },
        ),
        migrations.CreateModel(
            name="Step",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=64, verbose_name="name")),
                (
                    "instructions",
                    models.TextField(blank=True, verbose_name="instructions"),
                ),
                (
                    "stations",
                    models.ManyToManyField(
                        blank=True,
                        related_name="steps",
                        to="iris.station",
                        verbose_name="stations",
                    ),
                ),
            ],
            options={
                "verbose_name": "step",
                "verbose_name_plural": "steps",
            },
        ),
        migrations.CreateModel(
            name="StepTransition",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "creates",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.RESTRICT,
                        related_name="created_by",
                        to="iris.step",
                        verbose_name="creates",
                    ),
                ),
                (
                    "process",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="step_transitions",
                        to="iris.process",
                        verbose_name="process",
                    ),
                ),
            ],
            options={
                "verbose_name": "step transition",
                "verbose_name_plural": "step transitions",
            },
        ),
        migrations.CreateModel(
            name="Worker",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "user",
                    models.OneToOneField(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="user",
                    ),
                ),
            ],
            options={
                "verbose_name": "worker",
                "verbose_name_plural": "workers",
            },
        ),
        migrations.CreateModel(
            name="Task",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created",
                    models.DateTimeField(auto_now_add=True, verbose_name="created"),
                ),
                (
                    "modified",
                    models.DateTimeField(auto_now=True, verbose_name="modified"),
                ),
                (
                    "item",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.RESTRICT,
                        related_name="tasks",
                        to="iris.item",
                        verbose_name="item",
                    ),
                ),
                (
                    "step_transition",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.RESTRICT,
                        related_name="tasks",
                        to="iris.steptransition",
                        verbose_name="step transition",
                    ),
                ),
            ],
            options={
                "verbose_name": "task",
                "verbose_name_plural": "tasks",
            },
        ),
        migrations.CreateModel(
            name="Suspension",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created",
                    models.DateTimeField(auto_now_add=True, verbose_name="created"),
                ),
                (
                    "modified",
                    models.DateTimeField(auto_now=True, verbose_name="modified"),
                ),
                ("notes", models.TextField(blank=True, verbose_name="notes")),
                (
                    "lifted_at",
                    models.DateTimeField(
                        editable=False, null=True, verbose_name="lifted_at"
                    ),
                ),
                (
                    "task",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="suspensions",
                        to="iris.task",
                        verbose_name="task",
                    ),
                ),
                (
                    "worker",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.RESTRICT,
                        related_name="suspensions",
                        to="iris.worker",
                        verbose_name="worker",
                    ),
                ),
            ],
            options={
                "verbose_name": "suspension",
                "verbose_name_plural": "suspensions",
            },
        ),
        migrations.CreateModel(
            name="StepTransitionRequiredSteps",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "requirement",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="requirement",
                        to="iris.steptransition",
                    ),
                ),
                (
                    "step_transition",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="step_transition",
                        to="iris.steptransition",
                    ),
                ),
            ],
        ),
        migrations.AddField(
            model_name="steptransition",
            name="required_steps",
            field=models.ManyToManyField(
                related_name="required_by",
                through="iris.StepTransitionRequiredSteps",
                to="iris.steptransition",
                verbose_name="required steps",
            ),
        ),
        migrations.AddField(
            model_name="item",
            name="process",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="items",
                to="iris.process",
                verbose_name="process",
            ),
        ),
        migrations.CreateModel(
            name="Delay",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created",
                    models.DateTimeField(auto_now_add=True, verbose_name="created"),
                ),
                (
                    "modified",
                    models.DateTimeField(auto_now=True, verbose_name="modified"),
                ),
                ("notes", models.TextField(blank=True, verbose_name="notes")),
                ("duration", models.DurationField(verbose_name="duration")),
                (
                    "task",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="delays",
                        to="iris.task",
                        verbose_name="task",
                    ),
                ),
                (
                    "worker",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.RESTRICT,
                        related_name="delays",
                        to="iris.worker",
                        verbose_name="worker",
                    ),
                ),
            ],
            options={
                "verbose_name": "delay",
                "verbose_name_plural": "delays",
            },
        ),
        migrations.CreateModel(
            name="Commit",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created",
                    models.DateTimeField(auto_now_add=True, verbose_name="created"),
                ),
                (
                    "modified",
                    models.DateTimeField(auto_now=True, verbose_name="modified"),
                ),
                ("notes", models.TextField(blank=True, verbose_name="notes")),
                (
                    "task",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="iris.task",
                        verbose_name="task",
                    ),
                ),
                (
                    "worker",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.RESTRICT,
                        related_name="commits",
                        to="iris.worker",
                        verbose_name="worker",
                    ),
                ),
            ],
            options={
                "verbose_name": "commit",
                "verbose_name_plural": "commits",
            },
        ),
    ]
