# Generated by Django 4.2.1 on 2023-05-27 13:50

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("iris", "0013_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="item",
            name="process",
            field=models.ForeignKey(
                default=1,
                on_delete=django.db.models.deletion.RESTRICT,
                related_name="items",
                to="iris.process",
                verbose_name="process",
            ),
            preserve_default=False,
        ),
    ]
