@startuml
left to right direction

node "Iris internal site" {
  () "API" as API_IRIS
  API_IRIS -- [iris]
}

node "Company on-line store" {
  [wooiris]
}

[wooiris] ..> API_IRIS

"user"
user - [iris]

@enduml
