name: iris
on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Set up Python 3.11
      uses: actions/setup-python@v1
      with:
        python-version: 3.11
    - name: Install pip dependencies
      run: |
        pip3 install black~=23.3
        pip3 install isort~=5.12
    - name: Check styles with Black
      run: black --check manage.py iris deps/iris_wc
    - name: Check imports with isort
      run: isort --check manage.py iris deps/iris_wc
